version: "3"
services:
  mt:
    image: ${DOCKER_MT_IMAGE:-movabletype/test:perl-5.28}
    restart: always
    working_dir: /var/www/cgi-bin/mt
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    environment:
      NLS_LANG: ${NLS_LANG:-Japanese_Japan.UTF8}
      MT_DEV_UPDATE_BRANCH: ${UPDATE_BRANCH:-yes}
      DOCKER_MT_SERVICES: ${DOCKER_MT_SERVICES}
    volumes:
      - "..:/mt-dev"
      - "${MT_HOME_PATH:-../../movabletype}:/var/www/cgi-bin/mt"
      - "${MT_CONFIG_CGI_SRC_PATH:-../mt-config.cgi-original}:${MT_CONFIG_CGI_DEST_PATH:-/var/www/cgi-bin/mt/mt-config.cgi}"
      - "${BASE_SITE_PATH:-site}:/var/www/html"
      - "support:/var/www/cgi-bin/mt/mt-static/support"
      # override entrypoint
      - "./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"

  httpd:
    image: ${DOCKER_HTTPD_IMAGE:-movabletype/test:php-7.3}
    restart: always
    entrypoint: "/usr/local/bin/docker-entrypoint.sh"
    volumes:
      - "..:/mt-dev"
      - "${MT_HOME_PATH:-../../movabletype}:/var/www/cgi-bin/mt"
      - "${MT_CONFIG_CGI_SRC_PATH:-../mt-config.cgi-original}:${MT_CONFIG_CGI_DEST_PATH:-/var/www/cgi-bin/mt/mt-config.cgi}"
      - "${BASE_SITE_PATH:-site}:/var/www/html"
      - "support:/var/www/cgi-bin/mt/mt-static/support"
      # override entrypoint
      - "./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      # proxy setting
      - "./cgi-bin-mt.htaccess:/var/www/html/cgi-bin/mt/.htaccess"
      - "./cgi-bin-mt.htaccess:/var/www/cgi-bin/mt/.htaccess"
    ports:
      - "${HTTPD_EXPOSE_PORT:-80}:80"
    command: apache2-foreground

  mt-watcher:
    build:
      context: mt-watcher
    working_dir: /var/www/cgi-bin/mt
    environment:
      PERL_FNS_NO_OPT: ${PERL_FNS_NO_OPT:-0}
      DISABLE_MT_WATCHER: ${DISABLE_MT_WATCHER:-0}
    volumes:
      - "${MT_HOME_PATH:-../../movabletype}:/var/www/cgi-bin/mt"
      - "./mt-watcher.pl:/usr/local/lib/mt/bin/mt-watcher.pl"
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  site:
    driver: local
  support:
    driver: local
  mt-dev-mt-home-tmp:
    external: true
