version: "3"
services:
  mt:
    restart: always
    command: "${PLACKUP:-/usr/local/lib/mt/bin/plackup-mt} /var/www/cgi-bin/mt/mt.psgi"
    environment:
      MT_PID_FILE_PATH: ${MT_PID_FILE_PATH:-/tmp/mt.psgi.pid}
    volumes:
      - "./plackup-mt:/usr/local/lib/mt/bin/plackup-mt"
  mt-watcher:
    build:
      context: mt-watcher
    working_dir: /var/www/cgi-bin/mt
    command: /usr/local/lib/mt/bin/mt-watcher.pl
    environment:
      PERL_FNS_NO_OPT: ${PERL_FNS_NO_OPT:-0}
      DISABLE_MT_WATCHER: ${DISABLE_MT_WATCHER:-0}
    volumes:
      - "${MT_HOME_PATH:-../../movabletype}:/var/www/cgi-bin/mt"
      - "./mt-watcher.pl:/usr/local/lib/mt/bin/mt-watcher.pl"
      - /var/run/docker.sock:/var/run/docker.sock
